SPA/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include("SPA_app.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")))
]
urlpatterns += staticfiles_urlpatterns()

SPA_app/urls.py
from django.urls import path
from . import views

app_name = "SPA_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("contacts", views.contacts, name="contacts"),
    path("pharmacies", views.pharmacies, name="pharmacies")
]

SPA_app/models.py
from django.db import models


class Medicine(models.Model):
    title = models.CharField(max_length=255, verbose_name="title")
    photo = models.URLField(max_length=255, null=True, verbose_name="photo")
    price = models.FloatField(verbose_name="price")
    url = models.URLField(max_length=255, verbose_name="url")
    pharmacy = models.CharField(max_length=255, verbose_name="pharmacy")

    class Meta:
        verbose_name = "medicine"
        db_table = "medicine"


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name="title")
    photo = models.URLField(max_length=255, null=True, verbose_name="photo")

    class Meta:
        verbose_name = "product"
        db_table = "product"


class Pharmacy(models.Model):
    price = models.FloatField(verbose_name="price")
    url = models.URLField(max_length=255, verbose_name="url")
    pharmacy = models.CharField(max_length=255, verbose_name="pharmacy")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="product")

    class Meta:
        verbose_name = "pharmacy"
        db_table = "pharmacy"

scripts/planetazdorovo/models.py
from dataclasses import dataclass


@dataclass
class ItemModel:
    url: str
    image_url: str
    title: str
    price: float

SPA_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.core.paginator import Paginator, Page

from SPA.settings import MEILISEARCH_CLIENT


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "index.html")


def search(request: HttpRequest) -> HttpResponse:
    sort_list: dict = dict(name="по алфавиту", byprice="по возрастанию цены", bypricedesc="по убыванию цены")

    query = request.GET.get("query")
    if len(query) > 2:
        sort: str = request.GET.get("sort", default="name")
        page_number: int = int(request.GET.get("page", default=1))

        medicines: Page = __get_medicines(query, sort, page_number)

        return render(
            request, "search.html", {
                "medicines": medicines,
                "query": query,
                "sort_list": sort_list.items(),
                "sort": sort
            }
        )

    return redirect("SPA_app:index")


def pharmacies(request: HttpRequest) -> HttpResponse:
    return render(request, "pharmacies.html")


def contacts(request: HttpRequest) -> HttpResponse:
    return render(request, "contacts.html")


def __get_medicines(query: str, sort: str, page_number: int) -> Page:
    sort_list: dict = dict(name="title", byprice="price", bypricedesc="price")

    result: list = MEILISEARCH_CLIENT.index("medicines").search(query, {
        "attributesToHighlight": ["title"],
        "limit": 100000
    })["hits"][:300]
    result.sort(key=lambda item: item[sort_list.get(sort)], reverse=sort == "bypricedesc")

    paginator: Paginator = Paginator(result, 10)

    return paginator.get_page(page_number)

SPA_app/templates/contacts.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Контакты</title>
</head>
<body>
<div class="d-flex flex-column vh-90">
    <div class="d-flex flex-column justify-content-center align-items-center">
        <a href="{% url 'SPA_app:index' %}">
            <img src="{% static 'img/main-logo.svg' %}" class="img-fluid" style="width: 400px; height: 220px; margin: 20px;"
                 alt="Logo">
        </a>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h4>Наши контакты:</h4>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
        <p>По вопросам рекламы: <strong>ads@site.com</strong></p>
        <p>По вопросам сотрудничества: <strong>hi@site.com</strong></p>
    </div>
</div>
</body>
{% include 'footer.html' %}
</html>

SPA_app/templates/footer.html
<footer class="footer">
<div class="container">
    <div class="d-flex flex-row justify-content-between">
        <div class="d-flex">
            <h6 style="text-align: center; margin: 20px 0;">Мы работаем с аптеками г. Ульяновск</h6>
        </div>
        <div class="d-flex">
            <div class="p-3 text-secondary">
                <a class="underline" href="/pharmacies">Поддерживаемые аптеки</a>
            </div>
            <div class="p-3 text-secondary">
                <a class="underline" href="/contacts">Обратная связь</a>
            </div>
        </div>
    </div>
</div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

SPA_app/templates/index.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>SPA</title>
</head>
<body>
<div class="d-flex flex-column justify-content-center align-items-center vh-90">
    <div class="container">
        <img src="{% static 'img/main-logo.svg' %}" class="img-fluid mx-auto d-block"
             style="width: 400px; height: 220px; margin-bottom: 40px;">
        <form action="{% url 'SPA_app:search' %}" method="GET">
            <div class='d-flex flex-row w-75 mx-auto d-block' id="input-container">
                <input type="text" onkeyup="check_input()" name="query" class="border-0 text-input" placeholder="Введите название препарата">
                <input type="submit" class="border-0 btn" id="search_btn" value>
            </div>
        </form>
        <div id="validation" style="text-align: center;"></div>
    </div>
</div>
</body>
{% include 'footer.html' %}
 <script>
    function check_input(){
    if(document.querySelector('.text-input').value.length < 3){
        document.querySelector('#validation').innerHTML = "В названии должно быть минимум 3 символа";
    }
    else{
        document.querySelector('#validation').innerHTML = "";
    }
}
</script>
</html>

SPA_app/templates/pharmacies.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Аптеки</title>
</head>
<body>
<div class="d-flex flex-column justify-content-center align-items-center">
    <div>
        <a href="{% url 'SPA_app:index' %}">
            <img src="{% static 'img/main-logo.svg' %}" class="img-fluid" style="width: 300px; height: 170px; margin: 20px;" alt="Logo">
        </a>
    </div>
    <div class="container">
        <div class="mapWrapper">
            <iframe src="https://www.google.com/maps/d/embed?mid=1HRk8yCWz1CbEgGfVXYIVgo18hNhv0sCX"></iframe>
        </div>
    </div>
    <h3>Мы поддерживаем</h3>
    <div class="container">
        <div class="d-flex justify-content-evenly pharmacy flex-wrap">
            <a href="https://apteka.ru/" target="_blank">
                <img class="grayscale" src="{% static 'img/pharmacies/apteka-ru.jpg' %}" width="200px" height="67px"
                     alt="Apteka-ru">
            </a>
            <a href="https://zdravcity.ru/" target="_blank">
                <img class="grayscale" src="{% static 'img/pharmacies/zdravcity.jpg' %}" width="200px" height="67px"
                     alt="Zdravcity">
            </a>
            <a href="https://planetazdorovo.ru/" target="_blank">
                <img class="grayscale" src="{% static 'img/pharmacies/planeta_zdorovya.jpg' %}" width="200px"
                     height="67px" alt="PZ">
            </a>
            <a href="https://www.rigla.ru/" target="_blank">
                <img class="grayscale" src="{% static 'img/pharmacies/rigla.jpg' %}" width="200px" height="67px"
                     alt="Rigla">
            </a>
        </div>
    </div>
</div>
</body>
{% include 'footer.html' %}
</html>

SPA_app/templates/search.html
<!DOCTYPE html>
<html lang="ru" style="box-sizing: border-box;">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>SPA</title>
</head>
<body>
<header>
    <form action="{% url 'SPA_app:search' %}" method="GET">
        <div class="d-flex flex-wrap">
            <div style="padding-right: 30px;">
                <a class="navbar-brand" href="{% url 'SPA_app:index' %}">
                    <img src="{% static 'img/logo.svg' %}" width="150px" height="75px" style="margin: 10px; margin-bottom: 0;" alt="Logo">
                </a>
            </div>
            <div class='d-flex' style="width: 60%;" id="input-container">
                <input type="text" name="query" onkeyup="check_input()" class="border-0 text-input"
                       placeholder="Введите название препарата" value="{{ query }}">
                <input type="submit" class="border-0 btn" id="search_btn" value>
            </div>
        </div>
        <div id="validation" style="text-align: center;"></div>
        <hr class="search_line">
        <div class="container res_cont" id="sort-container">
            <p class="search-label">Результатов: {{ medicines.paginator.count }}</p>
            <div class="d-flex justify-content-evenly sort-main">
                <p class="search-label">Сортировка:</p>
                <select class="form-select" onchange="this.form.submit()" name="sort">
                    {% for value, name in sort_list %}
                        {% if value == sort %}
                            <option value="{{ value }}" selected>{{ name }}</option>
                        {% else %}
                            <option value="{{ value }}">{{ name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
    </form>
</header>
<div class="container res_cont">
    <div class="container" id="results" style="width: inherit; margin: 30px 0; padding-left: 0;">
        {% if medicines|length == 0 %}
            <h4 class="text-center">Увы, ничего не найдено</h4>
        {% else %}
            {% for medicine in medicines %}
                <div class='container' id="result-container">
                    <div id="medicine-info">
                        <div class="d-flex">
                            <img class="contain" src="{{ medicine.photo }}" width="100vw" height="100"
                             alt="{{ medicine.title }}">
                            <div class="product-info" style="word-break: break-word;">
                                <p>{{ medicine.title|title }}</p>
                                <p>от {{ medicine.price }} руб.</p>
                            </div>
                        </div>
                        <img src="{% static 'img/pharmacies/' %}{{ medicine.pharmacy }}.jpg" style="width: 150px;margin: auto 0 auto auto;">
                    </div>

                    <div class="float-end" id="arrow-container">
                        <a href="{{ medicine.url }}" target="_blank">
                            <img src="{% static 'img/right-arrow.png' %}" alt="Arrow">
                        </a>
                    </div>
                </div>
            {% endfor %}
            </div>
            <div class="container d-flex justify-content-center align-items-center" style="padding-right: 20%;">
                <div class="pagination" style="margin-left: auto; margin-right: auto;">
                        <span class="step-links">
                            {% if medicines.has_previous %}
                                <strong><a href="?query={{ query }}&sort={{ sort }}&page=1">&laquo; 1</a></strong>
                                <a href="?query={{ query }}&sort={{ sort }}&page={{ medicines.previous_page_number }}">← Предыдущая</a>
                            {% endif %}

                            <span class="current">{{ medicines.number }} из {{ medicines.paginator.num_pages }}</span>

                            {% if medicines.has_next %}
                                <a href="?query={{ query }}&sort={{ sort }}&page={{ medicines.next_page_number }}">Следующая →</a>
                                <strong><a
                                        href="?query={{ query }}&sort={{ sort }}&page={{ medicines.paginator.num_pages }}">
                                    {{ medicines.paginator.num_pages }} &raquo;
                                </a></strong>
                            {% endif %}
                        </span>
                </div>
            </div>
        {% endif %}
</div>
</body>
{% include 'footer.html' %}
 <script>
    function check_input(){
    if(document.querySelector('.text-input').value.length < 3){
        document.querySelector('#validation').innerHTML = "В названии должно быть минимум 3 символа";
    }
    else{
        document.querySelector('#validation').innerHTML = "";
    }
}
</script>
</html>